name: capstone-train
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.10
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - pip:
        - opencv-python
        - imageio==2.1.2
        - moviepy
        - keras==2.0.8
        - tensorflow-gpu==1.3
